### ISSUE TITLE
Audio still choppy sometimes

### ISSUE THREAD

**Issue by Raemon** [gwillen/solstice-audio-test#100]
Not sure if this exists anywhere else, but my sense from the tests so far is that audio still isn't super reliable. The way the robots sounded choppy was similar to how some singers sounded choppy at the previous run-through.

Possible partial-solution: I think there are a couple settings that maybe would be nice if we could tweak on the fly more easily? like, maybe quickly trying out "give the robots 4 seconds instead of 3 seconds". I'm not sure how many such settings there are, but it seemed like we need to figure out some way of handling poor connections better.

**Comment by harrislapiroff** [comment]
We tried to use this for an event yesterday and had this issue. It seemed like it maybe happened somewhere along the chain? People in the second position could very clearly hear the first person singing, but people in the third position onward complained that the audio was choppy and faint.

**Comment by jeffkaufman** [comment]
@harrislapiroff the bug you're describing sounds like the one fixed in https://github.com/gwillen/solstice-audio-test/commit/a661565c0815cb94efa1d2e4537214038d9748de, which was not deployed to echo.jefftk.com when you were testing.

I'm not sure whether Ray is describing the same bug, but I think his report is from after it was fixed on the server he was using?

**Comment by gwillen** [comment]
Faint audio is definitely that bug. "Choppy" I'm not sure, but anything where the _later_ person hears quieter or worse audio than an _earlier_ person sounds like that bug. In theory once audio is written it should stay the same forever after, except for that bug.

**Comment by harrislapiroff** [comment]
Perhaps it was a combination of both bugs? I would definitely describe the audio as choppy. (My personal experience actually, when I was third in line, was that _I think_ the first person's audio was faint but the second in line audio was choppy.)

**Comment by jeffkaufman** [comment]
I think all remaining choppiness people are running into (pretty rarely at this point) is due to poor network conditions, and not something we can fix
