### ISSUE TITLE
Chat not working

### ISSUE THREAD

**Issue by harrislapiroff** [gwillen/solstice-audio-test#101]
When we tried to use this yesterday with a group, chat wasn't working at all. Everyone could see their own messages, but no one saw anyone else's.

**Comment by jeffkaufman** [comment]
I confirmed that this is broken on echo.jefftk.com which was at 1953369d90b251097c392a3e479b3976578de1d4.  It is no longer broken at HEAD (955a6d8d4e78c909857e824153684dd3c4013060) so I'm guessing someone broke it a refactoring and then fixed it?

I've now updated production to HEAD and confirmed that it is no longer broken.  Sorry that chat didn't work in your singing event!
