### ISSUE TITLE
Sentry wants threads

### ISSUE THREAD

**Issue by jeffkaufman** [gwillen/solstice-audio-test#102]
In our logs, we are now getting:

```
/usr/local/lib/python3.6/dist-packages/sentry_sdk/_compat.py:84: Warning: We detected the use of uwsgi with disabled threads.  This will cause issues with the transport you are trying to use.  Please enable threading for uwsgi.  (Add the "enable-threads" flag).
```

We cannot enable threads, however, since our code is designed to use shared memory in a way that only works with a single thread. I don't know what sentry's issue is without them?

**Comment by taymonbeal** [comment]
From reading their code, I think the issue is that Sentry spawns a worker thread which consumes error reports from a queue and phones home with them, in order to avoid blocking its users' threads on a network call to the Sentry server.
