### ISSUE TITLE
Tried to switch back from audio chunks to placeholder chunks in handle_message!

### ISSUE THREAD

**Issue by jeffkaufman** [gwillen/solstice-audio-test#116]
When I am pushing the mixing consul really hard, with 1000 imaginary users, and I press the "lead a song" button I get the error:

    Tried to switch back from audio chunks to placeholder chunks in handle_message! This should never happen. Stale chunks in mic_buf?

![Screen Shot 2020-12-18 at 2 01 28 PM](https://user-images.githubusercontent.com/262566/102651013-c0e35f80-4139-11eb-8d46-58f6624e91a0.png)

**Comment by gwillen** [comment]
Thanks, this reproducer was critical in tracking the bug down, fixed in #121
