### ISSUE TITLE
[probably does not affect rE] race condition in stopping singing can cause a crash

### ISSUE THREAD

**Issue by gwillen** [gwillen/solstice-audio-test#120]
if a user sends stop_singing in their very first request, before they have a write clock assigned (which can happen if you are mashing all the buttons rapidly in testing), I believe it can cause song_end_clock to become null, which causes subsequent requests to crash.

I believe this cannot affect rE because in rE a user request will never attempt to end a song (the server does that.) Therefore I think we should leave it alone until solstice.

I think I may have introduced this in the refactor that added server-to-server requests, if it was not latent already.

The offending assignment is on server.py line 729, and the crash then happens on every request until another song is started, on server.py line 963:

`if user.last_write_clock <= state.song_end_clock <= client_write_clock:`
`TypeError: '<=' not supported between instances of 'int' and 'NoneType'`

**Comment by jeffkaufman** [comment]
Reading the code, I don't think this can happen anymore, and no one has reported it
