### ISSUE TITLE
Switching into server controlled mode should be more explicit

### ISSUE THREAD

**Issue by jeffkaufman** [gwillen/solstice-audio-test#126]
Somehow echo.jefftk.com is occasionally getting switched into server controlled mode, at which point many of the features of standalone bucket brigade do not work.

`if userid is None:` is not enough of a check; sometimes we get weird posts from robots.

For now, restarting the server fixes it, but that's not a good fix.

**Comment by jeffkaufman** [comment]
I think maybe I should just turn this off for now? And then if RE wants to reenable they can add an explicit marker?

**Comment by gwillen** [comment]
Makes sense to me. Turning off stuff for solstice was kind of a last-minute hack anyway. We can rethink how it works.

**Comment by jeffkaufman** [comment]
Yeah, the main problem is that it only takes one errant request from a bot and then we're stuck in this mode forever
