### ISSUE TITLE
Document server setup process better / clean up operations section of README

### ISSUE THREAD

**Issue by gwillen** [gwillen/solstice-audio-test#129]
As a reference, this doc I put together (which covers both Ritual Engine and Bucket Brigade): https://docs.google.com/document/d/1jn8vplVEnAmVOV6cw5Sua9th-SYKxYv1kPzuPGKAwxA/edit#heading=h.ydq4eumb7nmp

**Comment by jeffkaufman** [comment]
Fixed in 2f645fc5d714872750f3f4e1d2595cf010a71919
