### ISSUE TITLE
Enable some kind of "play existing audio backtrack"

### ISSUE THREAD

**Issue by Raemon** [gwillen/solstice-audio-test#14]
It's likely that we'll need to use a backing track for most (all?) songs at Solstice, to prevent a variety of logistical screwups. 

Eventually we'll need something fairly complex to handle an entire program of backup tracks, but for now just being able to play an existing link should be fine. I'm not sure about the implementation details.

**Comment by jeffkaufman** [comment]
I'm starting to play around with this

**Comment by Raemon** [comment]
A proto version of this now exists.
