### ISSUE TITLE
Clients should not be too persistent about 'dropped calls'

### ISSUE THREAD

**Issue by gwillen** [gwillen/solstice-audio-test#142]
Copying from comments of #131, so I don't forget to do a more comprehensive fix to this:

If we reconnect to the server, and we had some dropped process() calls we were trying to make up, we should flush them at that point.

If our count of dropped calls to make up for gets too high, we should give up and reconnect instead.
- This is worked-around in https://github.com/gwillen/solstice-audio-test/commit/b3026cc3e5d278d40aeeffe5d9aec2176dcd9d64 , but we should be able to clear state and reconnect without having to refresh the entire page.

The easy way to repro this is to put the computer to sleep while the client is running.

**Comment by jeffkaufman** [comment]
I think this is fine now
