### ISSUE TITLE
Video delay?

### ISSUE THREAD

**Issue by mgibbs** [gwillen/solstice-audio-test#185]
Would it be possible to delay the video in the same way that the audio is delayed?  It would be fun to be able to look at the video of everyone singing and get the visual of us all singing at the same time as well.  Had a really fun time singing tonight, really enjoyed this tool!

**Comment by jeffkaufman** [comment]
We don't currently know a technical way to delay the video, but I agree that it would be nice.

We're tracking ideas to do this in #153.
