### ISSUE TITLE
Needs a way to stop audio tracks when the lead singer loses their lead position

### ISSUE THREAD

**Issue by Raemon** [gwillen/solstice-audio-test#22]
I'm not 100% sure what was going on here, but it seemed like if the lead singer picked a backing track, and then lost their wifi, the audio track would keep playing forever.

**Comment by jeffkaufman** [comment]
As of now, if this happens the backing track will continue until it ends, which is a good default.

Another person can force it to end by pressing "take lead" and then "start singing" and then "end singing", which is kind of awkward.

We could add debug setting for forcing this, but it's an unusual thing to want to do, and I suspect this is a part of the system that we won't still be using when we have a solstice song-orchestration-and-ordering thing?
