### ISSUE TITLE
volume normalization thoughts

### ISSUE THREAD

**Issue by gwillen** [gwillen/solstice-audio-test#35]
* should be able to easily control volume of (1) backing track, (2) lead singers/instrumentalists, (3) audience as a group, to ensure that everybody can hear all three, but (1) and (2) get a configurable boost based on event runner's (or lead singers') taste.
* "ahead" of that, should automatically normalize everybody's volume to around the same level _before_ we apply those adjustments (or whatever other adjustments we like, e.g. turning down people who are off-key, if desired.) That can be done automatically by the browser, but I've seen several problems with that, so we should probably manage it ourselves. (One issue I've had, when testing this app, is long held notes getting detected as background noise and turned down to silence. Another issue, which I've had elsewhere when using Jitsi, is background noise, like computer fans, getting detected as quiet input and turned up to a roar.)

**Comment by gwillen** [comment]
(Also, regarding the "background noise getting automatically turned up" issue -- my friend with this problem reports that, on Windows, when you programmatically enable the automatic gain control in Chrome, this does not operate inside Chrome, but causes the underlying audio device volume control in Windows to get automatically adjusted, which he finds maddening. Another reason to avoid that setting perhaps.)

**Comment by jeffkaufman** [comment]
We've implemented most of these ideas at this point. If there are still things people want, that should probably be a separate issue and expressed relative to the status quo ;)
