### ISSUE TITLE
First-singer timing note (never assign anybody to time "0")

### ISSUE THREAD

**Issue by gwillen** [gwillen/solstice-audio-test#36]
This isn't exactly an "issue", but something I realized we aren't currently enforcing and maybe should be: The first client should NEVER connect at 0. I think right now we start them at 3, but this isn't enforced anywhere other than the randomization algorithm never picking 0.

The reason for this is that, now that we've introduced backing tracks, there is effectively always a singer at 0 if the backing track is enabled; and while the backing track takes up zero time (their 'write pointer' is right at 0), this still means that any request for audio _before_ 0, i.e. "in the future", will result in the backing track skipping for the first singer (in the same way that getting too close behind another singer will have the same effect.) And if you set your offset to 0, it _is_ possible for your actual read time to drift slightly negative, depending on various factors.

**Comment by jeffkaufman** [comment]
I don't think there is anything anymore that would put a singer at zero
