### ISSUE TITLE
stress testing

### ISSUE THREAD

**Issue by jeffkaufman** [gwillen/solstice-audio-test#41]
We should figure out what the maximum number of clients it can handle is, and figure out how to scale it if that's not good enough

**Comment by jeffkaufman** [comment]
I've updated `stress.py` to use multiple processes.

**Comment by jeffkaufman** [comment]
Testing on a wired MacBook Pro, I see average exceeding 600ms at ~55 clients:

```
$ python3 stress.py 55 15
[min=362  max=3752  avg=585]
$ python3 stress.py 55 45
[min=361  max=3524  avg=617]
```

Max starts to go bad ~28 clients:

```
 $ python3 stress.py 25 15
[min=359  max=881  avg=386]
 $ python3 stress.py 26 15
[min=364  max=885  avg=387]
 $ python3 stress.py 27 15
[min=364  max=524  avg=386]
 $ python3 stress.py 28 15
[min=359  max=1461  avg=393]
 $ python3 stress.py 28 15
[min=364  max=906  avg=400]
 $ python3 stress.py 28 15
[min=363  max=949  avg=391]
 $ python3 stress.py 29 15
[min=361  max=1429  avg=410]
 $ python3 stress.py 29 15
[min=363  max=1442  avg=409]
 $ python3 stress.py 29 15
[min=362  max=917  avg=405]
```

The main problem is I don't know whether this is a failing at the tester end or the server end.

**Comment by jeffkaufman** [comment]
Another problem is that I'm not currently testing with keep alive, so I think the server is working a bit harder than it should be

**Comment by jeffkaufman** [comment]
I made a version with keepalive (https://github.com/gwillen/solstice-audio-test/tree/keepalive-stress), but I think something is going wrong on my mac because I get lots of connection reset errors when I try it.

The ~300ms for connection setup goes away, though.

**Comment by jeffkaufman** [comment]
Stress testing only the python program I get:

```
    $ python3 unit-stress.py
    8.05ms each; est 75 clients
    8.12ms each; est 74 clients
    7.78ms each; est 77 clients
```

**Comment by jeffkaufman** [comment]
Even without opus it's not that fast:

```
$ python3 unit-stress.py noopus
2.65ms each; est 226 clients
2.59ms each; est 232 clients
2.60ms each; est 231 clients
```

**Comment by jeffkaufman** [comment]
When we also skip `pack_multi` and `unpack_multi` though it's very fast:

```
$ python3 unit-stress.py noopus nopack
0.25ms each; est 2432 clients
0.30ms each; est 2004 clients
0.35ms each; est 1731 clients
```

**Comment by gwillen** [comment]
Oh that's super promising, that's probably something we could push into a thread, or else figure out a way to do more efficiently. (Opus itself has a way to bundle frames into packets, but (1) the limit to the size of a packet is smaller than our request size, and (2) that functionality is not available on the JS side for us.)

**Comment by gwillen** [comment]
(Also the overhead of bundling and unbundling would go away if we went down to one opus frame per request, but I think we might have to go to websockets for that to be practical.)

**Comment by jeffkaufman** [comment]
Here's one idea for how we could do this:

* Start `N` (one for every ~50 users; server needs one core for each) uwsgi servers for decoding / encoding
* Tell nginx asked to choose one based on `userid % N`
* All N of the servers then maintain a connection to the core app over sockets, so our app can live entirely in "decoded" space
* No threading anywhere

**Comment by gwillen** [comment]
For reference, the numbers I get on my laptop:
```
(venv) bunneh:solstice-audio-test gwillen$ python3 unit-stress.py 
3.88ms each; est 155 clients
3.85ms each; est 156 clients
4.08ms each; est 147 clients
(venv) bunneh:solstice-audio-test gwillen$ python3 unit-stress.py  noopus
0.56ms each; est 1063 clients
0.54ms each; est 1111 clients
0.54ms each; est 1102 clients
(venv) bunneh:solstice-audio-test gwillen$ python3 unit-stress.py  noopus nopack
0.13ms each; est 4574 clients
0.18ms each; est 3259 clients
0.13ms each; est 4605 clients
(venv) bunneh:solstice-audio-test gwillen$ 
```

And on our current server:

```
root@solstice-audio-test:~/src/solstice-audio-test-notprod# python3 unit-stress.py 
6.18ms each; est 97 clients
6.40ms each; est 94 clients
6.37ms each; est 94 clients
root@solstice-audio-test:~/src/solstice-audio-test-notprod# python3 unit-stress.py  noopus
1.97ms each; est 304 clients
1.96ms each; est 306 clients
1.87ms each; est 321 clients
root@solstice-audio-test:~/src/solstice-audio-test-notprod# python3 unit-stress.py  noopus nopack
0.17ms each; est 3502 clients
0.17ms each; est 3583 clients
0.17ms each; est 3472 clients
```

So my read is that opus is like 70-90% of our time, depending, and to figure out exactly how bad the rest is in an absolute sense, we probably need a more realistic test.

**Comment by jeffkaufman** [comment]
I think we have 2-3 main approaches:

a) Shard but don't thread; what I proposed in https://github.com/gwillen/solstice-audio-test/issues/41#issuecomment-725782349.  This is more of a pain, but I'm quite confident in it and we don't have to worry about lock contention or threading bugs.

b) Threads.  Tell uWSGI to run many threads, have one big lock for all the shared stuff.  I think this ought to be able to get us to `noopus` levels of performance but not `noopus nopack`?

c) The approach in B, but additionally use some kind of python multiprocessing to offload the packing and unpacking as well.

**Comment by jeffkaufman** [comment]
I'm surprised that `noopus` -> `noopus nopack` is 4x on your laptop and 10x on the server

**Comment by gwillen** [comment]
on my laptop (running both the uwsgi server and the stress client there, without using nginx) I can run `stress.py 50 10` with no problems:

```
(venv) bunneh:solstice-audio-test gwillen$ python stress.py 50 10
[min=11  max=486  avg=137]
```

If I go up to 70, I don't get errors but the max exceeds 600 which seems like a not-great case:
```
(venv) bunneh:solstice-audio-test gwillen$ python stress.py 70 10
[min=11  max=791  avg=303]
```

I'm definitely going to need to fix the concurrency issues in the server before comparing with threading mode; if I naively turn on threads in uwsgi I immediately start getting 500s from the server that look like concurrency issues (indexing out of bounds in arrays.)

EDIT: I recall something about problems with longer runs, so I did one for a whole minute:

```
(venv) bunneh:solstice-audio-test gwillen$ python stress.py 70 100
[min=10  max=1456  avg=198]
```

I suspect actually the 'max' number is influenced by 'thundering herd' dynamics at the beginning when all the clients start up at once, and the realistic max is lower.

This is on a Core i7 3.1 GHz, using about 60% of a core (from eyeballing `top` output).

**Comment by gwillen** [comment]
One optimization we should do, while I'm thinking about it: if people are in the last layer, unless we're trying to record the whole mix we should just throw their audio away, and not send it to the server at all. Obviously for this to be useful, I'm assuming a setup where we have many people per layer.

**Comment by gwillen** [comment]
Added some profiling with cprofile: (This is on my laptop again running `stress.py 70 100`, which may be excessive, and with profiling overhead gives questionable stats, although zero errors: `[min=8  max=4479  avg=561]`)

```
         4020247 function calls in 48.916 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
    70000   26.084    0.000   26.742    0.000 /Users/gwillen/src/solstice-audio-test/venv/lib/python3.8/site-packages/opuslib/api/decoder.py:264(decode_float)
    70000    9.995    0.000   10.270    0.000 /Users/gwillen/src/solstice-audio-test/venv/lib/python3.8/site-packages/opuslib/api/encoder.py:157(encode_float)
     7000    2.386    0.000   48.149    0.007 server.py:280(handle_post)
     7001    1.494    0.000    1.494    0.000 /usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py:204(iterencode)
     7000    1.034    0.000    1.034    0.000 {method 'flush' of '_io.TextIOWrapper' objects}
     7000    0.760    0.000    0.773    0.000 server.py:265(unpack_multi)
   140000    0.718    0.000    0.718    0.000 /usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ctypes/__init__.py:506(cast)
     7007    0.561    0.000    0.988    0.000 server.py:235(user_summary)
   147000    0.515    0.000    0.515    0.000 {built-in method numpy.frombuffer}
    20997    0.507    0.000    0.528    0.000 server.py:136(wrap_assign)
     7000    0.315    0.000    0.320    0.000 /Users/gwillen/src/solstice-audio-test/venv/lib/python3.8/site-packages/opuslib/api/encoder.py:55(create_state)
     7000    0.275    0.000   48.880    0.007 server.py:673(do_POST)
     7140    0.236    0.000    0.236    0.000 {built-in method numpy.core._multiarray_umath.implement_array_function}
     7000    0.232    0.000    0.304    0.000 server.py:248(pack_multi)
     7007    0.219    0.000    0.219    0.000 {method 'sort' of 'list' objects}
     7000    0.194    0.000    0.196    0.000 server.py:211(clean_users)
   140000    0.189    0.000    0.189    0.000 {method 'tobytes' of 'array.array' objects}
    70000    0.187    0.000   26.947    0.000 /Users/gwillen/src/solstice-audio-test/venv/lib/python3.8/site-packages/opuslib/classes.py:66(decode_float)
     7428    0.178    0.000    0.178    0.000 {built-in method builtins.print}
    70000    0.173    0.000   10.461    0.000 /Users/gwillen/src/solstice-audio-test/venv/lib/python3.8/site-packages/opuslib/classes.py:183(encode_float)
     7000    0.170    0.000    0.320    0.000 /usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/logging/__init__.py:284(__init__)
   147000    0.168    0.000    0.168    0.000 {method 'tobytes' of 'numpy.ndarray' objects}
     7000    0.157    0.000    0.276    0.000 /usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/parse.py:689(parse_qsl)
   717834    0.129    0.000    0.129    0.000 {method 'append' of 'list' objects}
   486834    0.129    0.000    0.129    0.000 {built-in method builtins.round}
   728127    0.124    0.000    0.124    0.000 {built-in method builtins.len}
    27997    0.104    0.000    0.104    0.000 {built-in method numpy.zeros}
     7002    0.091    0.000    0.091    0.000 {uwsgi_spit}
```

(There's more, but at this point we start seeing initialization of the encoders and decoders, and other stuff that amortizes out.)

**Comment by jeffkaufman** [comment]
I've added locking support.

Before deploying, it could do 56 clients (55 simulated and one real), and sometimes was ok with 61, definiteltynot ok with 66.

After deploying it was stable at 61 but couldn't do more.

I do see uwsgi at > 100% CPU in top.

I'm not convinced that we are properly using both cores though.  The sharding approach still seems more more promising to me.

**Comment by jeffkaufman** [comment]
When the locks are not contested they don't seem to have any overhead, however, so I'll plan to leave them for now.

I've also left the prod server configured with two threads for now.

**Comment by jeffkaufman** [comment]
I ran some local testing on a 12-core server I have access to, comparing `/home/jkaufman/.local/bin/uwsgi --http :8081 --wsgi-file server_wrapper.py --disable-logging` to `/home/jkaufman/.local/bin/uwsgi --http :8081 --threads=12 --wsgi-file server_wrapper.py --disable-logging`.  Running it single threaded was higher capacity, believe it or not.  I also couldn't get uwsgi CPU, as reported in top, to go over 200%

**Comment by gwillen** [comment]
Hmm, seems like there is definitely something wrong then. It sounds like it's not really threading at all. I will take a look when I get a chance and see if I see anything.

**Comment by jeffkaufman** [comment]
With two threads, however I was able to get a slightly better performance than with one thread. I wonder if we're able to take advantage of hyperthreading but not of multiple CPUs?

(This CPU reports as having six cores, 12 threads.)

**Comment by jeffkaufman** [comment]
Anyway, this is all making me think that we should have N processes that all RPC to a single process

**Comment by jeffkaufman** [comment]
I've started work on this, using shared memory for inter-process communication

**Comment by jeffkaufman** [comment]
I've committed this as it is; there is still more work needed:

* Python errors in server.py need to be caught and passed to the client across the shm boundary
* Set up systemd service files on the server
* Set up nginx routing on the server
* Update load testing to be able to shard
* Run load testing
* Update client to be able to shard

The server is still running in single process mode; I'll update here when I change that

**Comment by jeffkaufman** [comment]
`Python errors in server.py need to be caught and passed to the client across the shm boundary` -> done

`Set up systemd service files on the server` -> done

`Set up nginx routing on the server` -> done

`Update load testing to be able to shard` -> done

`Run load testing` -> no improvement

But it's possible that the reason there's no improvements that we only have two cores to work with? And you wouldn't really expect this approach to start doing better until you got to at least three.

I'm going to try testing on a 6 core / 12 thread server

**Comment by jeffkaufman** [comment]
Initially I had trouble because the user summary got so big I couldn't fit it in shared memory. After turning it off however, I was able to run a test with 750 "users" using five of the 12-core machines as clients:

```
$ python3 stress.py 150 60 8
[min=4  max=273  avg=87]
```

And one as the server:

![Screen Shot 2020-11-13 at 1 31 23 PM](https://user-images.githubusercontent.com/262566/99108119-e0c0ba00-25b4-11eb-8cfe-5923a733eeec.png)

The python3 process is the central coordinating one, and it only got up to about 50% CPU.

I wasn't using nginx, so there's a bit of risk there, but I think at this point we have a solution that can scale to maybe 1k users if we run it on a sufficiently large server.

**Comment by jeffkaufman** [comment]
I had it configured with eight uwsgi processes, and my limitation was client machines to hammer it from.  Seems like it probably could've done more?

**Comment by jeffkaufman** [comment]
Another source of risk is that I am currently sending it empty audio. It is possible that real audio would be more work to decode?

**Comment by jeffkaufman** [comment]
Instead of having each client simulate a real client by only sending one request every 600 ms, we just had them send request as fast as possible, we wouldn't need so many client machines to test with.

**Comment by jeffkaufman** [comment]
I added a "sleepless" version of stress testing, which is slightly less realistic because it is not actually a large number of clients, but stresses the server much harder at less effort: `python3 stress.py 4 100 4 "http://localhost:81%s" nosleep`

**Comment by jeffkaufman** [comment]
One downside of the "sleepless" version is that it would not have caught the problem where when we have a zillion clients user_summary gets too big.

**Comment by jeffkaufman** [comment]
We can fix this some with d7177cd which adds `users_per_client` and makes each of these super fast clients run through a range of user IDs: `python3 stress.py 4 10 100 4 "http://localhost:81%s" nosleep`

**Comment by jeffkaufman** [comment]
With the most current test scripts in nosleep mode and the user summary disabled (#50) on the same 6-processor 12-thread (`Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz`), I'm seeing us handling ~216 clients unsharded and ~1090 with 8 shards.

**Comment by jeffkaufman** [comment]
I wrote this up as a blog post: https://www.jefftk.com/p/sharding-the-brigade

**Comment by jeffkaufman** [comment]
At this point I think we are able to stress test, and are able to go to sufficiently quickly by applying more hardware; closing this.
