### ISSUE TITLE
When testing in chrome on a mobile device it says I am not using chrome

### ISSUE THREAD

**Issue by calvinballing** [gwillen/solstice-audio-test#44]
Device: iPhone XR
Chrome version: 86.0.4240.93

After tapping the dismiss button, it showed the following error:

TypeError: undefined is not When testing in chrome on a mobile device it says I am not using chromean object (evaluating 'navigator.permissions.query')
https://echo.jefftk.com/app.js:162:48
asyncFunctionResume@[native code]
https://echo.jefftk.com/app.js:1632:33
asyncFunctionResume@[native code]
module code@https://echo.jefftk.com/app.js:1698:11
evaluate@[native code]
moduleEvaluation@[native code]
[native code]
promiseReactionJob@[native code]

**Comment by jeffkaufman** [comment]
Unfortunately, Chrome on iOS is not really Chrome. All browsers on iOS are a thin wrapper around Safari, and so only support the APIs that Safari implements. Safari has not yet built out support for audio worklets, and so the app does not work there yet. There isn't currently any way to get this to work on an iPhone, sorry!

We should update the error message, and other messaging, however, to make this clear.

**Comment by jeffkaufman** [comment]
This is now fixed. We still won't support iPhones, but at least now I we'll give them a sensible error message
