### ISSUE TITLE
Website crashed

### ISSUE THREAD

**Issue by vivarose** [gwillen/solstice-audio-test#45]
I was leading Seasons of Love and there was one other friend.

The website said it crashed, but it was still playing Seasons of Love.

Here's the error code:
Error: Cannot decode non-contiguous chunks!
Error: Cannot decode non-contiguous chunks!
    at AudioDecoder.decode_chunk (https://echo.jefftk.com/app.js:803:13)
    at MessagePort.handle_message (https://echo.jefftk.com/app.js:1288:36)

**Comment by jeffkaufman** [comment]
Tracking this in https://github.com/gwillen/solstice-audio-test/issues/28
