### ISSUE TITLE
Clarify ordering of singers

### ISSUE THREAD

**Issue by z3nabi** [gwillen/solstice-audio-test#47]
The text currently says "choose a number between 6 and 116", but then when you click on "Lead Song" it gives you a number below 6. Also, it's currently important to not pick an order before someone clicks the "Lead" button which could also be clarified in the text

Even more ideal would be a more intuitive user interface -- e.g. the order dialog could pop up only once someone clicks "Lead".

**Comment by jeffkaufman** [comment]
This should be a lot better in the new user interface
