### ISSUE TITLE
Add the option to listen to/download the recorded song afterwards

### ISSUE THREAD

**Issue by z3nabi** [gwillen/solstice-audio-test#49]

**Comment by jeffkaufman** [comment]
I think the way this should work is that when someone presses start singing we look at what delays we have signed and figure out the soonest point at which we would expect to have everyone's contribution. Then we start streaming this to disk as an uncompressed wav file, stopping when either someone presses stop singing or it's been, say, 10 minutes. These could all be in a folder with an index, and some sort of automatic cleanup enabled so we don't end up with a ridiculously huge amount of disk usage. People would need to download their songs pretty promptly not to lose them.
