### ISSUE TITLE
Computing the user summary is expensive

### ISSUE THREAD

**Issue by jeffkaufman** [gwillen/solstice-audio-test#50]
When testing with 1600 simulated users, I get about twice the throughput if I don't include the user summary

We are computing it for every user in response to every request, but it seems to me like we could cache it, and only update it when its inputs change.

On the other hand, it's possible that this summer is just not how we wanna handle things at all? It doesn't really make sense after you get to a very large number of users, and I'm already truncating it to just the first 50. With very large numbers of users, I think this should really only be going to whoever is running the soundboard?

**Comment by taymonbeal** [comment]
I dunno about your demo app, but for Solstice I don't currently intend to feed any data about other singers to each singer; only the admin interface needs that. (But that's obviously not finalized yet, other people might have different ideas.)
