### ISSUE TITLE
page crashed while I wasn't singing

### ISSUE THREAD

**Issue by vivarose** [gwillen/solstice-audio-test#52]
I had left myself connected, thinking I would sing a song, do some work, then sing another song. Maybe I can't do that? When I came back to the page, I saw the following message:

Error: Cannot decode non-contiguous chunks!
Error: Cannot decode non-contiguous chunks!
    at AudioDecoder.decode_chunk (https://echo.jefftk.com/app.js:887:13)
    at MessagePort.handle_message (https://echo.jefftk.com/app.js:1377:36)

**Comment by jeffkaufman** [comment]
Thanks! It seems like we have a problem where occasionally responses are handled out of order?

Tracking this in #28
