### ISSUE TITLE
Track user volumes, and send to sound person

### ISSUE THREAD

**Issue by jeffkaufman** [gwillen/solstice-audio-test#68]
The only way the sound person can currently set levels is by listening to someone and seeing how their levels should change. On the other hand, sometimes someone will sing very quietly during volume calibration and then much louder in the real thing. For each user, send their most recent average acoustic energy (RMS of most recent packet) to the person running sound.

This means levels will update every 600 milliseconds, and to be about 2 seconds out of date, but this is a good place to start.

**Comment by EEdwardsA** [comment]
Jeff and I fixed this!
