### ISSUE TITLE
Best practices

### ISSUE THREAD

**Issue by gwillen** [gwillen/solstice-audio-test#70]
We should make sure we have all the best practices for using the app together in one place, and show them during the 'tutorial'. For example:

- No bluetooth headphones / bluetooth audio devices of any kind
- Wired network (vs WiFi), if possible
- Close all other tabs, or as many as possible
- Close any unnecessary apps

(Obviously video chat is effectively necessary for using the app, and most people won't be able to move that to another machine, but it might be worth mentioning as a last resort.)

**Comment by jeffkaufman** [comment]
In addition, we should have a page people can link to which describes the requirements ahead of time.

Another requirement that belongs on here is chrome

**Comment by gwillen** [comment]
Agreed. And at least tentatively, another requirement is "desktop chrome", i.e. not mobile.

**Comment by gwillen** [comment]
I think we also maybe should recommend people use an incognito window / disable extensions.

**Comment by jeffkaufman** [comment]
These are now instructions https://echo.jefftk.com/#Reserve
