### ISSUE TITLE
A way to upload backing tracks

### ISSUE THREAD

**Issue by gwillen** [gwillen/solstice-audio-test#89]
Would be good to have a way to upload backing tracks through the web interface. Ideally handling all the conversion steps automatically, and renaming the file to the specified target name.

**Comment by jeffkaufman** [comment]
Alternatively, perhaps they should be ephemeral, similar to lyrics.

**Comment by jeffkaufman** [comment]
Here's an initial version:

* Add a new service, responsible for handling backing track uploads
* Have nginx proxy_pass `/upload` to it
* The upload service reads the bytes from the request, decodes any compression, and writes to `audio/User Upload`

Later on, we can save the original name to `audio/user_upload_fname.txt` or something, pass that to clients, and special case it in backing track selection.
