### ISSUE TITLE
Handle someone is singing substantially louder than they calibrated at

### ISSUE THREAD

**Issue by jeffkaufman** [gwillen/solstice-audio-test#92]
If someone sings timidly during volume calibration, and then enthusiastically during the real thing, they will end up much louder than everyone else. Similarly, if somebody moves closer to their microphone between calibration and actually singing, you will get the same effect.

One way to fix this is to run the volume calibration routine all the time, and if someone is substantially louder than we calibrated them, automatically turn them down

**Comment by Raemon** [comment]
Related situations I'm worried about are "a nearby baby or lawnmower
suddenly screams" – I'm not sure if this is meaningfully different from the
other situations you've listed but seems like "short punctuated loudness"
might need to be handled different from "people is overall louder than we
thought they were going to be". Maybe generally if you're Suddenly Real
Loud past a particular absolute threshold, you always get turned down?

**Comment by jeffkaufman** [comment]
Implemented in https://github.com/gwillen/solstice-audio-test/pull/93.  If you are too loud, it turns you down permanently.  It puts a message in the console when it does this.

We may eventually want something more sophisticated, where when someone is very temporarily too loud, we only temporarily turn them down?

Similarly, if someone is consistently quite a bit louder than they were calibrated at, it would be nice to turn them down a little bit.
